### ISSUE TITLE
In dire need of update

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [Plisio/plisio-python#1]
Hello. 
Can the maintainers issue an update for the latest Python version and also changes made to the Plisio's API. Many things are broken in the python library and even simple examples no longer run. Also crypto-currency names are outdated too in addition to API names, etc.

**Comment by amiwrpremium** [comment]
Hi.
I had the same problem and I decided to write a new package.


Available at: 
[Github](https://github.com/amiwrpremium/python-plisio)
[PyPi](https://pypi.org/project/python-plisio/)

**Comment by RuVl** [comment]
Can you complement documentation of your library (for example: how to install? Should I add 'plisio' to settings.py? And more information about function parameters)?
